buildDeps:
  - hs-build-tools
  - maven3
  - node-20.11.0

buildType: CENTOS8

env:
  SHOULD_APPLY_USER_TO_COMMANDS: true  # Remove once Blazar applies this by default

containers:
  - name: main
    securityContext: unprivileged
    user: hs-build
    image: docker.hubteam.com/wailmer/blazar-executor-centos8:993

steps:
  - description: Build with gradle
    expandSegmentByDefault: true
    container: main
    commands:
      - ./gradlew :hubspot:build --no-daemon --stacktrace --info

